services:
  backend:
    build: ./ecom
    ports:
      - "8000:8000"
    volumes:
      - ./ecom:/app
    environment:
      SECRET_KEY: ${SECRET_KEY}

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend